const orderActionTypes = {
  SET_SELECTED_ITEM: "SET_SELECTED_ITEM",
  SET_SELECTED_ITEMS: "SET_SELECTED_ITEMS",
  SET_SHIPPING_ADDRESS: "SET_SHIPPING_ADDRESS",
  SET_PAYMENT_DETAILS: "SET_PAYMENT_DETAILS",
  SAVE_ORDER_START: "SAVE_ORDER_START",
  SAVE_ORDER_SUCCESS: "SAVE_ORDER_SUCCESS",
  SAVE_ORDER_ERROR: "SAVE_ORDER_ERROR",
};
export default orderActionTypes;
