const orderActionTypes = {
  SET_SELECTED_ITEM: "SET_SELECTED_ITEM",
  SET_SELECTED_ITEMS: "SET_SELECTED_ITEMS",
  SET_SHIPPING_ADDRESS: "SET_SHIPPING_ADDRESS",
  SET_PAYMENT_DETAILS: "SET_PAYMENT_DETAILS",
};
export default orderActionTypes;
