const userActionTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNIN_ERROR: "SIGNIN_ERROR",
  SIGNOUT_ERROR: "SIGNOUT_ERROR",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
};
export default userActionTypes;
